[package]
name = "agent-wire-node"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
agent-wire-compute-market = { path = "../compute-market" }
agent-wire-foundation.workspace = true
agent-wire-relay-market = { path = "../relay-market" }
agent-wire-storage-market = { path = "../storage-market" }
agent-wire-transport-cloudflare = { path = "../transport-cloudflare" }
